version: "3.1"
services:
  db:
    container_name: postgres
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
    - backbone
    ports:
    - 127.0.0.1:5432:5432
    volumes:
      - ./scripts/database-startup.sh:/docker-entrypoint-initdb.d/database-startup.sh

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    networks:
    - backbone

networks:
  backbone: