apiVersion: apps/v1
kind: Deployment
metadata:
  name: 23ws-ase-pr-inso-06-release-backend
  namespace: 23ws-ase-pr-inso-06
spec:
  selector:
    matchLabels:
      app: 23ws-ase-pr-inso-06-release-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: 23ws-ase-pr-inso-06-release-backend
    spec:
      volumes:
        - name: release-database-connection-string
          secret:
            secretName: release-database-connection-string
      imagePullSecrets:
      - name: secret-dockercfg
      containers:
        - name: release-backend
          image: registry.reset.inso-w.at/2023ws-ase-pr-group/23ws-ase-pr-inso-06/release-backend:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "1000Mi"
              cpu: "500m"
              ephemeral-storage: "100Mi"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: 80
              path: /health
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 80
              path: /health
          volumeMounts:
            - mountPath: /var/backend/database.json
              name: release-database-connection-string
              readOnly: true
              subPath: database.json
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
---
apiVersion: v1
kind: Service
metadata:
  name: s-23ws-ase-pr-inso-06-release-backend-service
  namespace: 23ws-ase-pr-inso-06
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: 23ws-ase-pr-inso-06-release-backend
  ports:
    - port: 80
      name: "backend"