apiVersion: apps/v1
kind: Deployment
metadata:
  name: 23ws-ase-pr-inso-06-release-frontend
  namespace: 23ws-ase-pr-inso-06
spec:
  selector:
    matchLabels:
      app: 23ws-ase-pr-inso-06-release-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: 23ws-ase-pr-inso-06-release-frontend
    spec:
      imagePullSecrets:
      - name: secret-dockercfg
      containers:
        - name: release-frontend
          image: registry.reset.inso-w.at/2023ws-ase-pr-group/23ws-ase-pr-inso-06/release-frontend:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "100Mi"
          ports:
            - containerPort: 80
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
---
apiVersion: v1
kind: Service
metadata:
  name: s-23ws-ase-pr-inso-06-release-frontend-service
  namespace: 23ws-ase-pr-inso-06
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: 23ws-ase-pr-inso-06-release-frontend
  ports:
    - port: 80
      name: "http"
    - port: 443
      name: "https"